
####################################################################################
# Generated by Vivado 2012.2.OR0 built on 'Tue May 15 18:59:13 MDT 2012' by 'xbuild'
####################################################################################




## LOC's 



## These constraints are defined for Virtex 7 Device: xc7v585t-ffg1761-2. 
## Please modify according to your selected device
##set_property PACKAGE_PIN  AT22 [get_ports refclk125_p]
##set_property PACKAGE_PIN  AU22 [get_ports refclk125_n]
##set_property IOSTANDARD LVDS [get_ports refclk125_n]
##set_property IOSTANDARD LVDS [get_ports refclk125_p]
##set_property IOSTANDARD LVCMOS18 [get_ports reset]
##set_property PACKAGE_PIN  AY34 [get_ports reset]
##set_property PACKAGE_PIN  AU29 [get_ports rxp]
##set_property PACKAGE_PIN  AV29 [get_ports rxn]
##set_property IOSTANDARD LVDS_25 [get_ports rxn]
##set_property IOSTANDARD LVDS_25 [get_ports rxp]
##set_property PACKAGE_PIN  BB28 [get_ports txp]
##set_property PACKAGE_PIN  BB29 [get_ports txn]
##set_property IOSTANDARD LVDS_25 [get_ports txn]
##set_property IOSTANDARD LVDS_25 [get_ports txp]  


# Global
# ------

# Period of the reference clock that feeds the MMCM.  MMCM output clocks periods
# and their constraints will be automatically derived.

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# In xdc, all clocks are related by default. This differs from ucf, where clocks are unrelated unless specified otherwise. As a result, you may now see cross-clock paths that were previously unconstrained in ucf. Commented out xdc false path constraints have been generated and can be uncommented, should you wish to remove these new paths. These commands are located after the last clock definition
create_clock -name refclk125 -period 8.000 [get_ports refclk125_p]

set_false_path -to [get_pins */core_resets_i/rst_dly_reg*/PRE]
