# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mrenda/research/xvc_microserver/core/VC707/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
# IP: The module: 'gig_ethernet_pcs_pma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mrenda/research/xvc_microserver/core/VC707/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/mrenda/research/xvc_microserver/core/VC707/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/mrenda/research/xvc_microserver/core/VC707/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/mrenda/research/xvc_microserver/core/VC707/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
# IP: The module: 'gig_ethernet_pcs_pma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mrenda/research/xvc_microserver/core/VC707/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/mrenda/research/xvc_microserver/core/VC707/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/mrenda/research/xvc_microserver/core/VC707/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gig_ethernet_pcs_pma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
